#!/usr/bin/env python3
"""Validate locale keys/placeholders and generate immutable embedded resources.
Add locales via registry.json; missing keys intentionally fall back to English.
"""
from pathlib import Path
import json
import re
root = Path(__file__).resolve().parents[1]
base = root / 'resources/locales'
registry = json.loads((base/'registry.json').read_text())
locales = registry['locales']
ids = [item['id'] for item in locales]
assert len(ids) == len(set(ids)) and registry['default'] in ids and registry['fallback'] in ids
baseline = json.loads((base/(registry['fallback']+'.json')).read_text())
q = lambda value: json.dumps(value, ensure_ascii=False)
lines = ['// Generated by scripts/generate_i18n.py; do not edit.', '#include "i18n.hpp"', 'namespace i18n {']
all_text = ''.join(item['name'] for item in locales)
for i, meta in enumerate(locales):
    values = json.loads((base/(meta['id']+'.json')).read_text())
    assert not values.keys() - baseline.keys(), f"Unknown keys in {meta['id']}"
    for key, value in values.items():
        assert set(re.findall(r'\{(\w+)\}', value)) == set(re.findall(r'\{(\w+)\}', baseline[key])), f'Placeholder mismatch {meta["id"]}:{key}'
    missing = baseline.keys() - values.keys()
    if missing:
        print(f'{meta["id"]}: {len(missing)} missing keys use {registry["fallback"]}')
    lines.append(f'static const Entry entries_{i}[] = {{')
    for key, value in sorted(values.items()):
        lines.append(f'  {{{q(key)}, {q(value)}}},')
        all_text += value
    lines += ['};']
lines += ['const Locale locales[] = {']
for i, meta in enumerate(locales):
    lines.append(f' {{{q(meta["id"])}, {q(meta["name"])}, {q(meta["font"])}, entries_{i}, sizeof(entries_{i})/sizeof(Entry)}},')
lines += ['};', 'const size_t locale_count = sizeof(locales)/sizeof(Locale);', f'const char *default_locale = {q(registry["default"])};', f'const char *fallback_locale = {q(registry["fallback"])};', '}']
(root/'core/i18n_generated.cpp').write_text('\n'.join(lines)+'\n')
# Keep glyphs used by native language names in every selectable font family.
characters = ''.join(sorted(set(c for c in all_text if ord(c) > 127)))
(root/'fonts/characters.txt').write_text(characters)
print(f'Validated {len(locales)} locales, {len(baseline)} keys, {len(characters)} non-ASCII glyphs')
